ALTER TABLE "Submission" ADD COLUMN IF NOT EXISTS "feedback" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Submission" ADD COLUMN IF NOT EXISTS "imageName" TEXT;
ALTER TABLE "Submission" ADD COLUMN IF NOT EXISTS "imageMimeType" TEXT;
ALTER TABLE "Submission" ADD COLUMN IF NOT EXISTS "imageData" BYTEA;
ALTER TABLE "Submission" ADD COLUMN IF NOT EXISTS "screenshotName" TEXT;
ALTER TABLE "Submission" ADD COLUMN IF NOT EXISTS "screenshotMimeType" TEXT;
ALTER TABLE "Submission" ADD COLUMN IF NOT EXISTS "screenshotData" BYTEA;
